### PR TITLE
Update 03-security-principles.md

### PR DESCRIPTION
**Pull request by sydseter**
Add the principle of compartmentalize

**Summary** :  

I feel the "[The Compartmentalization principle](https://en.wikipedia.org/wiki/Compartmentalization_(information_security))" is missing. I think this would bridge "The Least privilege" principle with the  "Economy of Mechanism".

This is also mentioned in "[Building Secure Software: How to Avoid Security Problems the Right Way](https://www.amazon.com/Building-Secure-Software-Security-Documents-ebook/dp/B003CW67YQ/ref=sr_1_1?crid=UV4FKMAKB5EV&dib=eyJ2IjoiMSJ9.Vkfz6-jqiSz4swfILu_CaA.qoW8VG8f8AjovY0S2eNKRi-8mpmm_4V9j6o0hH3KLZI&dib_tag=se&keywords=Building+Secure+Software%3A+How+to+Avoid+Security+Problems+the+Right+Way&qid=1723450640&s=digital-text&sprefix=building+secure+software+how+to+avoid+security+problems+the+right+way%2Cdigital-text%2C388&sr=1-1)" by John Viega and Gary McGraw on p. 102-105.

**Description for the changelog** :  

Adding the compartmentalize principle.

**Other info** :  

John Viega: https://www.amazon.com/stores/John-Viega/author/B001H9PYUE?ref=ap_rdr&isDramIntegrated=true&shoppingPortalEnabled=true

Gary McGraw: https://www.amazon.com/stores/Gary-McGraw/author/B000APFZ2S?ref=ap_rdr&isDramIntegrated=true&shoppingPortalEnabled=true

### CODE REVIEW

**Review by jgadsden — APPROVED** [review]
thanks again @sydseter , do you want to go ahead and merge? I think you now have the permissions

**Comment by sydseter** [comment]
@jgadsden Great Jon, thanks again. I am not yet a contributor, but wouldn't mind becoming on.

**Comment by jgadsden** [comment]
> @jgadsden Great Jon, thanks again. I am not yet a contributor, but wouldn't mind becoming on.

I recently added you, so the invite may be stuck in your email box somewhere

**Comment by sydseter** [comment]
Oh yes, my bad, thanks.

**Pull request merged**
