### PR TITLE
Update 01-open-source-software.md

### PR DESCRIPTION
**Pull request by Shruti-s-kulkarni**
**Summary** :  

**Description for the changelog** :  

**Other info** :

### CODE REVIEW

**Review by Shruti-s-kulkarni — COMMENTED** [review]
All good, please review offline

**Comment by jgadsden** [comment]
This seems to be a duplicate of #49 , so closing it

**Review by jgadsden — COMMENTED** [review]
This seems to be a duplicate of #49  , so closing it

**Review by Shruti-s-kulkarni — COMMENTED** [review]
No changes made
ready for merge into main branch

**Pull request closed without merging**
