### PR TITLE
Update to new OWASP Top 10 Proactive Controls

### LINKED ISSUE #272: Update links to the new OWASP Top 10 Proactive Controls
**Describe what change you would like** :  
The OWASP Top 10 Proactive Controls have had a new release with different controls and different links
These need to be updated

**Context** :  
Section: 07-implementation/01-documentation/01-proactive-controls
also some references in 06-design/02-web-app-checklist and 05-requirements/01-requirements

### PR DESCRIPTION
**Pull request by andreashappe**
**Summary** :  

Update links to the new OWASP Top 10 Proactive Controls

**Description for the changelog** :  

Update links to the new OWASP Top 10 Proactive Controls. This would be important as google actually provides the developer guide as first hit when searching for "owasp proactive controls" (:

**Other info** :  

I am one of the OWASP Top 10 co-leaders.

closes #272 'Update links to the new OWASP Top 10 Proactive Controls'

### CODE REVIEW

**Comment by jgadsden** [comment]
Thanks for this @andreashappe , our nightly link checker had started to complain :)
there is a markdown lint warning about multiple blank lines if you want to change that?

**Review by jgadsden — APPROVED** [review]
many thanks for this @andreashappe , good to have the links fixed up and updated for the new release of proactive controls
there are some links in other parts of the DevGuide - I am happy to fix them up if you like?

**Comment by andreashappe** [comment]
> many thanks for this @andreashappe , good to have the links fixed up and updated for the new release of proactive controls there are some links in other parts of the DevGuide - I am happy to fix them up if you like?

That would be amazing!

**Comment by jgadsden** [comment]
@andreashappe I think this patch might work as a starting point for the other fixups:
[patch-1.diff.txt](https://github.com/user-attachments/files/16868297/patch-1.diff.txt)

**Comment by andreashappe** [comment]
> @andreashappe I think this patch might work as a starting point for the other fixups: [patch-1.diff.txt](https://github.com/user-attachments/files/16868297/patch-1.diff.txt) although I missed your last two commits, so a lot of it is out of date - apologies

will look at it -- but I think I should be down to 6-7 wrong links anyways

**Comment by jgadsden** [comment]
> @jgadsden I am a bit confused by the open issues, I don't really see them in the source code

Hello @andreashappe , thanks for fixing up the other sections - much better than my suggestions 👍🏾 

the changes in `draft/05-requirements/00-toc.md` should be copied over into `draft/05-requirements/toc.md` and that should sort out the link check. It is a bit clunky to have to copy the changes over, it was to do with HTML docs and PDF/eBook docs differences

the spellcheck is flagging line 19 of `draft/06-design/02-web-app-checklist/03-secure-database-access.md`, and then that should be all that is needed to merge

**Comment by jgadsden** [comment]
BTW, you are now a contributor to the modified pages, did you want to add your name to the modified files line 6? You are most welcome as these are important changes

**Comment by andreashappe** [comment]
> BTW, you are now a contributor to the modified pages, did you want to add your name to the modified files line 6? You are most welcome as these are important changes

sure, what format should I use? (json array, comma-separated list)?

**Comment by andreashappe** [comment]
semi-related question: while creating the new OWASP OT Top 10 list, I am also writing a 'best practises for new projects' document that hopefully will help other new projects. Can I use https://github.com/OWASP/www-project-developer-guide/blob/main/.github/workflows/ci.yaml for that? Including something like that would make a lot of sense (:

**Comment by jgadsden** [comment]
> Can I use https://github.com/OWASP/www-project-developer-guide/blob/main/.github/workflows/ci.yaml for that?

Yes, of course @andreashappe , I am honored!

**Review by jgadsden — APPROVED** [review]
all good, thanks again @andreashappe 
and please go ahead with the merge

**Pull request merged**
